export default 
{ "travelers": 
    [
        {"id":1,"name":"Alden Johnson","travelerType":"history buff"},
        {"id":2,"name":"Jocelyn Nguyen","travelerType":"shopper"},
        {"id":3,"name":"Lena Patel","travelerType":"relaxer"},
        {"id":4,"name":"Caleb Richards","travelerType":"foodie"},
        {"id":5,"name":"Elena Thompson","travelerType":"photographer"},
        {"id":6,"name":"Sofia Martinez","travelerType":"thrill-seeker"},
        {"id":7,"name":"Mateo Hernandez","travelerType":"history buff"},
        {"id":8,"name":"Isabella Smith","travelerType":"relaxer"},
        {"id":9,"name":"William Taylor","travelerType":"shopper"},
        {"id":10,"name":"Olivia Brown","travelerType":"thrill-seeker"},
        {"id":11,"name":"Lucas Lee","travelerType":"photographer"},
        {"id":12,"name":"Emma Wilson","travelerType":"foodie"},
        {"id":13,"name":"Ethan Garcia","travelerType":"relaxer"},
        {"id":14,"name":"Sophia Rodriguez","travelerType":"history buff"},
        {"id":15,"name":"Michael Martinez","travelerType":"shopper"},
        {"id":16,"name":"Avery Hernandez","travelerType":"photographer"},
        {"id":17,"name":"Mia Jones","travelerType":"thrill-seeker"},
        {"id":18,"name":"Logan Davis","travelerType":"foodie"},
        {"id":19,"name":"Amelia Nguyen","travelerType":"relaxer"},
        {"id":20,"name":"Elijah Wilson","travelerType":"history buff"},
        {"id":21,"name":"Charlotte Brown","travelerType":"shopper"},
        {"id":22,"name":"Benjamin Thomas","travelerType":"photographer"},
        {"id":23,"name":"Mason Garcia","travelerType":"thrill-seeker"},
        {"id":24,"name":"Harper Martinez","travelerType":"foodie"},
        {"id":25,"name":"Evelyn Hernandez","travelerType":"relaxer"},
        {"id":26,"name":"Liam Wilson","travelerType":"history buff"},
        {"id":27,"name":"Elizabeth Johnson","travelerType":"shopper"},
        {"id":28,"name":"Alexander Brown","travelerType":"photographer"},
        {"id":29,"name":"Abigail Lee","travelerType":"thrill-seeker"},
        {"id":30,"name":"James Smith","travelerType":"foodie"},
        {"id":31,"name":"Sofia Garcia","travelerType":"relaxer"},
        {"id":32,"name":"Oliver Rodriguez","travelerType":"history buff"},
        {"id":33,"name":"Charlotte Martinez","travelerType":"shopper"},
        {"id":34,"name":"Lucas Brown","travelerType":"photographer"},
        {"id":35,"name":"Emma Thomas","travelerType":"thrill-seeker"},
        {"id":36,"name":"Mia Davis","travelerType":"foodie"},
        {"id":37,"name":"Liam Nguyen","travelerType":"relaxer"},
        {"id":38,"name":"Olivia Wilson","travelerType":"history buff"},
        {"id":39,"name":"Ava Hernandez","travelerType":"shopper"},
        {"id":40,"name":"Noah Johnson","travelerType":"photographer"},
        {"id":41,"name":"Sophia Brown","travelerType":"thrill-seeker"},
        {"id":42,"name":"Michael Martinez","travelerType":"foodie"},
        {"id":43,"name":"Isabella Lee","travelerType":"relaxer"},
        {"id":44,"name":"Ethan Wilson","travelerType":"history buff"},
        {"id":45,"name":"Charlotte Davis","travelerType":"shopper"},
        {"id":46,"name":"Oliver Brown","travelerType":"photographer"},
        {"id":47,"name":"Avery Thomas","travelerType":"thrill-seeker"},
        {"id":48,"name":"Emma Garcia","travelerType":"foodie"},
        {"id":49,"name":"Benjamin Nguyen","travelerType":"relaxer"},
        {"id":50,"name":"Elizabeth Hernandez","travelerType":"history buff"}
    ]
}
